// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: protos/user/source/common.proto

package uspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents user status's enum values.
type Status int32

const (
	Status_ACTIVE   Status = 0
	Status_INACTIVE Status = 1
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "ACTIVE",
		1: "INACTIVE",
	}
	Status_value = map[string]int32{
		"ACTIVE":   0,
		"INACTIVE": 1,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_user_source_common_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_protos_user_source_common_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_protos_user_source_common_proto_rawDescGZIP(), []int{0}
}

var File_protos_user_source_common_proto protoreflect.FileDescriptor

var file_protos_user_source_common_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2f, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x12, 0x75, 0x73, 0x65, 0x72, 0x2e, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2a, 0x22, 0x0a, 0x06, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x0a, 0x0a, 0x06, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x49,
	0x4e, 0x41, 0x43, 0x54, 0x49, 0x56, 0x45, 0x10, 0x01, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b,
	0x75, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_user_source_common_proto_rawDescOnce sync.Once
	file_protos_user_source_common_proto_rawDescData = file_protos_user_source_common_proto_rawDesc
)

func file_protos_user_source_common_proto_rawDescGZIP() []byte {
	file_protos_user_source_common_proto_rawDescOnce.Do(func() {
		file_protos_user_source_common_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_user_source_common_proto_rawDescData)
	})
	return file_protos_user_source_common_proto_rawDescData
}

var file_protos_user_source_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_user_source_common_proto_goTypes = []interface{}{
	(Status)(0), // 0: user.source.common.Status
}
var file_protos_user_source_common_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_user_source_common_proto_init() }
func file_protos_user_source_common_proto_init() {
	if File_protos_user_source_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_user_source_common_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_user_source_common_proto_goTypes,
		DependencyIndexes: file_protos_user_source_common_proto_depIdxs,
		EnumInfos:         file_protos_user_source_common_proto_enumTypes,
	}.Build()
	File_protos_user_source_common_proto = out.File
	file_protos_user_source_common_proto_rawDesc = nil
	file_protos_user_source_common_proto_goTypes = nil
	file_protos_user_source_common_proto_depIdxs = nil
}
