// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/user/source/common.proto

package uspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Status represents user status's enum values.
type Status int32

const (
	Status_ACTIVE   Status = 0
	Status_INACTIVE Status = 1
)

var Status_name = map[int32]string{
	0: "ACTIVE",
	1: "INACTIVE",
}

var Status_value = map[string]int32{
	"ACTIVE":   0,
	"INACTIVE": 1,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_09e674285638c635, []int{0}
}

func init() {
	proto.RegisterEnum("user.source.common.Status", Status_name, Status_value)
}

func init() { proto.RegisterFile("protos/user/source/common.proto", fileDescriptor_09e674285638c635) }

var fileDescriptor_09e674285638c635 = []byte{
	// 99 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0x2f, 0xd6, 0x2f, 0x2d, 0x4e, 0x2d, 0xd2, 0x2f, 0xce, 0x2f, 0x2d, 0x4a, 0x4e, 0xd5, 0x4f,
	0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x03, 0xcb, 0x08, 0x09, 0x81, 0x64, 0xf4, 0x20, 0x32, 0x7a,
	0x10, 0x19, 0x2d, 0x25, 0x2e, 0xb6, 0xe0, 0x92, 0xc4, 0x92, 0xd2, 0x62, 0x21, 0x2e, 0x2e, 0x36,
	0x47, 0xe7, 0x10, 0xcf, 0x30, 0x57, 0x01, 0x06, 0x21, 0x1e, 0x2e, 0x0e, 0x4f, 0x3f, 0x28, 0x8f,
	0x31, 0x89, 0x0d, 0xac, 0xdd, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x62, 0x7d, 0x1c, 0xbb, 0x61,
	0x00, 0x00, 0x00,
}
