// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/user/source/request.proto

package uspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request schema for calling Delete on user.
type UserDestroyRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDestroyRequest) Reset()         { *m = UserDestroyRequest{} }
func (m *UserDestroyRequest) String() string { return proto.CompactTextString(m) }
func (*UserDestroyRequest) ProtoMessage()    {}
func (*UserDestroyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0568eec7c95e7b1, []int{0}
}

func (m *UserDestroyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDestroyRequest.Unmarshal(m, b)
}
func (m *UserDestroyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDestroyRequest.Marshal(b, m, deterministic)
}
func (m *UserDestroyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDestroyRequest.Merge(m, src)
}
func (m *UserDestroyRequest) XXX_Size() int {
	return xxx_messageInfo_UserDestroyRequest.Size(m)
}
func (m *UserDestroyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDestroyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserDestroyRequest proto.InternalMessageInfo

func (m *UserDestroyRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

// The request schema for calling Update on user.
type UserUpdateRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	Status               Status   `protobuf:"varint,6,opt,name=status,proto3,enum=user.source.common.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateRequest) Reset()         { *m = UserUpdateRequest{} }
func (m *UserUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*UserUpdateRequest) ProtoMessage()    {}
func (*UserUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0568eec7c95e7b1, []int{1}
}

func (m *UserUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateRequest.Unmarshal(m, b)
}
func (m *UserUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateRequest.Marshal(b, m, deterministic)
}
func (m *UserUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateRequest.Merge(m, src)
}
func (m *UserUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_UserUpdateRequest.Size(m)
}
func (m *UserUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateRequest proto.InternalMessageInfo

func (m *UserUpdateRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserUpdateRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserUpdateRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserUpdateRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserUpdateRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserUpdateRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ACTIVE
}

// The request schema for calling Store on user.
type UserStoreRequest struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Status               Status   `protobuf:"varint,5,opt,name=status,proto3,enum=user.source.common.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStoreRequest) Reset()         { *m = UserStoreRequest{} }
func (m *UserStoreRequest) String() string { return proto.CompactTextString(m) }
func (*UserStoreRequest) ProtoMessage()    {}
func (*UserStoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0568eec7c95e7b1, []int{2}
}

func (m *UserStoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStoreRequest.Unmarshal(m, b)
}
func (m *UserStoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStoreRequest.Marshal(b, m, deterministic)
}
func (m *UserStoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStoreRequest.Merge(m, src)
}
func (m *UserStoreRequest) XXX_Size() int {
	return xxx_messageInfo_UserStoreRequest.Size(m)
}
func (m *UserStoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserStoreRequest proto.InternalMessageInfo

func (m *UserStoreRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserStoreRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserStoreRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserStoreRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UserStoreRequest) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ACTIVE
}

// The request schema for calling Find on user.
type UserFindRequest struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFindRequest) Reset()         { *m = UserFindRequest{} }
func (m *UserFindRequest) String() string { return proto.CompactTextString(m) }
func (*UserFindRequest) ProtoMessage()    {}
func (*UserFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0568eec7c95e7b1, []int{3}
}

func (m *UserFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFindRequest.Unmarshal(m, b)
}
func (m *UserFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFindRequest.Marshal(b, m, deterministic)
}
func (m *UserFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFindRequest.Merge(m, src)
}
func (m *UserFindRequest) XXX_Size() int {
	return xxx_messageInfo_UserFindRequest.Size(m)
}
func (m *UserFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserFindRequest proto.InternalMessageInfo

func (m *UserFindRequest) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*UserDestroyRequest)(nil), "user.source.request.UserDestroyRequest")
	proto.RegisterType((*UserUpdateRequest)(nil), "user.source.request.UserUpdateRequest")
	proto.RegisterType((*UserStoreRequest)(nil), "user.source.request.UserStoreRequest")
	proto.RegisterType((*UserFindRequest)(nil), "user.source.request.UserFindRequest")
}

func init() { proto.RegisterFile("protos/user/source/request.proto", fileDescriptor_e0568eec7c95e7b1) }

var fileDescriptor_e0568eec7c95e7b1 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0x49, 0x77, 0xb7, 0x6c, 0x07, 0x5c, 0x35, 0x7a, 0x28, 0x15, 0xb1, 0x16, 0x0f, 0x3d,
	0xb5, 0xb0, 0xbe, 0x82, 0x78, 0xf4, 0xd0, 0x65, 0xcf, 0x12, 0xb7, 0x23, 0x14, 0x36, 0x4d, 0xcd,
	0xa4, 0x88, 0xef, 0xe5, 0x2b, 0xf8, 0x5e, 0x92, 0xa4, 0x2b, 0x0a, 0x46, 0x3c, 0x66, 0xbe, 0xff,
	0x87, 0x6f, 0x26, 0x90, 0x0f, 0x5a, 0x19, 0x45, 0xf5, 0x48, 0xa8, 0x6b, 0x52, 0xa3, 0xde, 0x61,
	0xad, 0xf1, 0x65, 0x44, 0x32, 0x95, 0x43, 0xfc, 0xcc, 0xa2, 0xca, 0xa3, 0x6a, 0x42, 0xd9, 0xd5,
	0x2f, 0xb5, 0x9d, 0x92, 0x52, 0xf5, 0xbe, 0x55, 0xdc, 0x00, 0xdf, 0x12, 0xea, 0x3b, 0x24, 0xa3,
	0xd5, 0x5b, 0xe3, 0x6b, 0x7c, 0x05, 0x51, 0xd7, 0xa6, 0x2c, 0x67, 0xe5, 0x51, 0x13, 0x75, 0x6d,
	0xf1, 0xc1, 0xe0, 0xd4, 0xc6, 0xb6, 0x43, 0x2b, 0x0c, 0x06, 0x52, 0xfc, 0x12, 0xe0, 0xb9, 0xd3,
	0x64, 0x1e, 0x7b, 0x21, 0x31, 0x8d, 0x72, 0x56, 0x26, 0x4d, 0xe2, 0x26, 0x0f, 0x42, 0x22, 0xbf,
	0x80, 0x64, 0x2f, 0x0e, 0x74, 0xe6, 0xe8, 0xd2, 0x0e, 0x1c, 0x3c, 0x87, 0x05, 0x4a, 0xd1, 0xed,
	0xd3, 0xb9, 0x03, 0xfe, 0xc1, 0x33, 0x58, 0x0e, 0x82, 0xe8, 0x55, 0xe9, 0x36, 0x5d, 0xf8, 0xc6,
	0xe1, 0xcd, 0xd7, 0x10, 0x93, 0x11, 0x66, 0xa4, 0x34, 0xce, 0x59, 0xb9, 0x5a, 0x67, 0xd5, 0xf7,
	0x03, 0x4c, 0x4b, 0x6e, 0x5c, 0xa2, 0x99, 0x92, 0xc5, 0x3b, 0x83, 0x13, 0xbb, 0xc7, 0xc6, 0x28,
	0xfd, 0xb5, 0xc6, 0x4f, 0x6d, 0xf6, 0xa7, 0x76, 0x14, 0xd2, 0x9e, 0x85, 0xb4, 0xe7, 0x41, 0xed,
	0xc5, 0xbf, 0xb5, 0xaf, 0xe1, 0xd8, 0x5a, 0xdf, 0x77, 0x7d, 0x1b, 0xb8, 0xfd, 0x53, 0xec, 0xbe,
	0xf3, 0xf6, 0x33, 0x00, 0x00, 0xff, 0xff, 0x67, 0x20, 0x36, 0x38, 0x28, 0x02, 0x00, 0x00,
}
