// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/user/source/response.proto

package uspb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The response you get for calling Store on user.
type UserStoreResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Status               Status   `protobuf:"varint,6,opt,name=status,proto3,enum=user.source.common.Status" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStoreResponse) Reset()         { *m = UserStoreResponse{} }
func (m *UserStoreResponse) String() string { return proto.CompactTextString(m) }
func (*UserStoreResponse) ProtoMessage()    {}
func (*UserStoreResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82057921c5aee194, []int{0}
}

func (m *UserStoreResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStoreResponse.Unmarshal(m, b)
}
func (m *UserStoreResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStoreResponse.Marshal(b, m, deterministic)
}
func (m *UserStoreResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStoreResponse.Merge(m, src)
}
func (m *UserStoreResponse) XXX_Size() int {
	return xxx_messageInfo_UserStoreResponse.Size(m)
}
func (m *UserStoreResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStoreResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserStoreResponse proto.InternalMessageInfo

func (m *UserStoreResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserStoreResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserStoreResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserStoreResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserStoreResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ACTIVE
}

func (m *UserStoreResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserStoreResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// The response you get for calling Find on user.
type UserFindResponse struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName            string   `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Status               Status   `protobuf:"varint,6,opt,name=status,proto3,enum=user.source.common.Status" json:"status,omitempty"`
	CreatedAt            int64    `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserFindResponse) Reset()         { *m = UserFindResponse{} }
func (m *UserFindResponse) String() string { return proto.CompactTextString(m) }
func (*UserFindResponse) ProtoMessage()    {}
func (*UserFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82057921c5aee194, []int{1}
}

func (m *UserFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserFindResponse.Unmarshal(m, b)
}
func (m *UserFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserFindResponse.Marshal(b, m, deterministic)
}
func (m *UserFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserFindResponse.Merge(m, src)
}
func (m *UserFindResponse) XXX_Size() int {
	return xxx_messageInfo_UserFindResponse.Size(m)
}
func (m *UserFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserFindResponse proto.InternalMessageInfo

func (m *UserFindResponse) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserFindResponse) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *UserFindResponse) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *UserFindResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UserFindResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_ACTIVE
}

func (m *UserFindResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *UserFindResponse) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

// The response you get for calling Delete on user.
type UserDestroyResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserDestroyResponse) Reset()         { *m = UserDestroyResponse{} }
func (m *UserDestroyResponse) String() string { return proto.CompactTextString(m) }
func (*UserDestroyResponse) ProtoMessage()    {}
func (*UserDestroyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82057921c5aee194, []int{2}
}

func (m *UserDestroyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserDestroyResponse.Unmarshal(m, b)
}
func (m *UserDestroyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserDestroyResponse.Marshal(b, m, deterministic)
}
func (m *UserDestroyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserDestroyResponse.Merge(m, src)
}
func (m *UserDestroyResponse) XXX_Size() int {
	return xxx_messageInfo_UserDestroyResponse.Size(m)
}
func (m *UserDestroyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserDestroyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserDestroyResponse proto.InternalMessageInfo

func (m *UserDestroyResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// The response you get for calling Update on user.
type UserUpdateResponse struct {
	Status               bool     `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserUpdateResponse) Reset()         { *m = UserUpdateResponse{} }
func (m *UserUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*UserUpdateResponse) ProtoMessage()    {}
func (*UserUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_82057921c5aee194, []int{3}
}

func (m *UserUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserUpdateResponse.Unmarshal(m, b)
}
func (m *UserUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserUpdateResponse.Marshal(b, m, deterministic)
}
func (m *UserUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserUpdateResponse.Merge(m, src)
}
func (m *UserUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_UserUpdateResponse.Size(m)
}
func (m *UserUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserUpdateResponse proto.InternalMessageInfo

func (m *UserUpdateResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func init() {
	proto.RegisterType((*UserStoreResponse)(nil), "user.source.response.UserStoreResponse")
	proto.RegisterType((*UserFindResponse)(nil), "user.source.response.UserFindResponse")
	proto.RegisterType((*UserDestroyResponse)(nil), "user.source.response.UserDestroyResponse")
	proto.RegisterType((*UserUpdateResponse)(nil), "user.source.response.UserUpdateResponse")
}

func init() { proto.RegisterFile("protos/user/source/response.proto", fileDescriptor_82057921c5aee194) }

var fileDescriptor_82057921c5aee194 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x92, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xd9, 0x56, 0x63, 0x32, 0x60, 0xd1, 0xb5, 0x48, 0xa8, 0x88, 0x31, 0xa7, 0x1c, 0x34,
	0x81, 0xfa, 0x0b, 0x0a, 0xe2, 0xd1, 0x43, 0x4a, 0xcf, 0x65, 0x4d, 0x46, 0x08, 0x34, 0xd9, 0xb0,
	0x33, 0x39, 0xf8, 0x87, 0xf5, 0x6f, 0xc8, 0x6e, 0x36, 0xc5, 0x83, 0xe0, 0xdd, 0xe3, 0xbe, 0xef,
	0x3d, 0xf6, 0x3d, 0x18, 0xb8, 0xef, 0x8d, 0x66, 0x4d, 0xc5, 0x40, 0x68, 0x0a, 0xd2, 0x83, 0xa9,
	0xb0, 0x30, 0x48, 0xbd, 0xee, 0x08, 0x73, 0xc7, 0xe4, 0xd2, 0xb2, 0x7c, 0x64, 0xf9, 0xc4, 0x56,
	0x77, 0xbf, 0x04, 0x2b, 0xdd, 0xb6, 0xba, 0x1b, 0x63, 0xe9, 0x97, 0x80, 0xcb, 0x1d, 0xa1, 0xd9,
	0xb2, 0x36, 0x58, 0xfa, 0x98, 0x5c, 0xc0, 0xac, 0xa9, 0x63, 0x91, 0x88, 0xec, 0xbc, 0x9c, 0x35,
	0xb5, 0xbc, 0x05, 0x78, 0x6f, 0x0c, 0xf1, 0xbe, 0x53, 0x2d, 0xc6, 0xb3, 0x44, 0x64, 0x51, 0x19,
	0x39, 0xe5, 0x55, 0xb5, 0x28, 0x6f, 0x20, 0x3a, 0xa8, 0x89, 0xce, 0x1d, 0x0d, 0xad, 0xe0, 0xe0,
	0x12, 0x4e, 0xb1, 0x55, 0xcd, 0x21, 0x3e, 0x71, 0x60, 0x7c, 0xc8, 0x35, 0x04, 0xc4, 0x8a, 0x07,
	0x8a, 0x83, 0x44, 0x64, 0x8b, 0xf5, 0x2a, 0xff, 0xd9, 0xdf, 0x57, 0xdc, 0x3a, 0x47, 0xe9, 0x9d,
	0xb6, 0x45, 0x65, 0x50, 0x31, 0xd6, 0x7b, 0xc5, 0xf1, 0x59, 0x22, 0xb2, 0x79, 0x19, 0x79, 0x65,
	0xc3, 0x16, 0x0f, 0x7d, 0x3d, 0xe1, 0x70, 0xc4, 0x5e, 0xd9, 0x70, 0xfa, 0x29, 0xe0, 0xc2, 0x2e,
	0x7d, 0x69, 0xba, 0xfa, 0x5f, 0x0f, 0x7d, 0x84, 0x2b, 0xbb, 0xf3, 0x19, 0x89, 0x8d, 0xfe, 0x38,
	0x4e, 0xbd, 0x3e, 0x16, 0xb1, 0x73, 0xc3, 0xe9, 0xb3, 0xf4, 0x01, 0xa4, 0xb5, 0xef, 0x5c, 0xfe,
	0x2f, 0xf7, 0x5b, 0xe0, 0xce, 0xe6, 0xe9, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x80, 0x9a, 0x0e, 0xb7,
	0x92, 0x02, 0x00, 0x00,
}
