server:
  host: ""
  port: 80

services:
  edible:
    address: "restaurant_edible_app:80"

  user:
    address: "restaurant_user_app:80"

# auth:
#   endpoint: "localhost:9090"
#   clients:
#     order:
#       client_id: "gateway_order"
#       client_secret: "0rd3r53cr37"
#     menu:
#       client_id: "gateway_menu"
#       client_secret: "m3nu53cr37"
