// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: protos/order/submission/response.proto

package ospb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The response you get for calling Submit on order.
type OrderSubmitResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *OrderSubmitResponse) Reset() {
	*x = OrderSubmitResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_order_submission_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderSubmitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderSubmitResponse) ProtoMessage() {}

func (x *OrderSubmitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_order_submission_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderSubmitResponse.ProtoReflect.Descriptor instead.
func (*OrderSubmitResponse) Descriptor() ([]byte, []int) {
	return file_protos_order_submission_response_proto_rawDescGZIP(), []int{0}
}

func (x *OrderSubmitResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_protos_order_submission_response_proto protoreflect.FileDescriptor

var file_protos_order_submission_response_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x73,
	0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2e,
	0x73, 0x75, 0x62, 0x6d, 0x69, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x2d, 0x0a, 0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x75, 0x62, 0x6d,
	0x69, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x6f, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_order_submission_response_proto_rawDescOnce sync.Once
	file_protos_order_submission_response_proto_rawDescData = file_protos_order_submission_response_proto_rawDesc
)

func file_protos_order_submission_response_proto_rawDescGZIP() []byte {
	file_protos_order_submission_response_proto_rawDescOnce.Do(func() {
		file_protos_order_submission_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_order_submission_response_proto_rawDescData)
	})
	return file_protos_order_submission_response_proto_rawDescData
}

var file_protos_order_submission_response_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protos_order_submission_response_proto_goTypes = []interface{}{
	(*OrderSubmitResponse)(nil), // 0: order.submission.response.OrderSubmitResponse
}
var file_protos_order_submission_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_order_submission_response_proto_init() }
func file_protos_order_submission_response_proto_init() {
	if File_protos_order_submission_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_order_submission_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderSubmitResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_order_submission_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_order_submission_response_proto_goTypes,
		DependencyIndexes: file_protos_order_submission_response_proto_depIdxs,
		MessageInfos:      file_protos_order_submission_response_proto_msgTypes,
	}.Build()
	File_protos_order_submission_response_proto = out.File
	file_protos_order_submission_response_proto_rawDesc = nil
	file_protos_order_submission_response_proto_goTypes = nil
	file_protos_order_submission_response_proto_depIdxs = nil
}
