// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: protos/order/submission/service.proto

package ospb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// OrderSubmissionServiceClient is the client API for OrderSubmissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderSubmissionServiceClient interface {
	// Unary
	Submit(ctx context.Context, in *OrderSubmitRequest, opts ...grpc.CallOption) (*OrderSubmitResponse, error)
}

type orderSubmissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderSubmissionServiceClient(cc grpc.ClientConnInterface) OrderSubmissionServiceClient {
	return &orderSubmissionServiceClient{cc}
}

func (c *orderSubmissionServiceClient) Submit(ctx context.Context, in *OrderSubmitRequest, opts ...grpc.CallOption) (*OrderSubmitResponse, error) {
	out := new(OrderSubmitResponse)
	err := c.cc.Invoke(ctx, "/order.submission.service.OrderSubmissionService/Submit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderSubmissionServiceServer is the server API for OrderSubmissionService service.
// All implementations should embed UnimplementedOrderSubmissionServiceServer
// for forward compatibility
type OrderSubmissionServiceServer interface {
	// Unary
	Submit(context.Context, *OrderSubmitRequest) (*OrderSubmitResponse, error)
}

// UnimplementedOrderSubmissionServiceServer should be embedded to have forward compatible implementations.
type UnimplementedOrderSubmissionServiceServer struct {
}

func (UnimplementedOrderSubmissionServiceServer) Submit(context.Context, *OrderSubmitRequest) (*OrderSubmitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Submit not implemented")
}

// UnsafeOrderSubmissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderSubmissionServiceServer will
// result in compilation errors.
type UnsafeOrderSubmissionServiceServer interface {
	mustEmbedUnimplementedOrderSubmissionServiceServer()
}

func RegisterOrderSubmissionServiceServer(s grpc.ServiceRegistrar, srv OrderSubmissionServiceServer) {
	s.RegisterService(&OrderSubmissionService_ServiceDesc, srv)
}

func _OrderSubmissionService_Submit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderSubmitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderSubmissionServiceServer).Submit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/order.submission.service.OrderSubmissionService/Submit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderSubmissionServiceServer).Submit(ctx, req.(*OrderSubmitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OrderSubmissionService_ServiceDesc is the grpc.ServiceDesc for OrderSubmissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderSubmissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.submission.service.OrderSubmissionService",
	HandlerType: (*OrderSubmissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Submit",
			Handler:    _OrderSubmissionService_Submit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/order/submission/service.proto",
}
