// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: protos/edible/inventory/request.proto

package eipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request schema for calling Recycle on inventory.
type InventoryRecycleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecycleFinished bool `protobuf:"varint,1,opt,name=recycle_finished,json=recycleFinished,proto3" json:"recycle_finished,omitempty"`
	RecycleExpired  bool `protobuf:"varint,2,opt,name=recycle_expired,json=recycleExpired,proto3" json:"recycle_expired,omitempty"`
}

func (x *InventoryRecycleRequest) Reset() {
	*x = InventoryRecycleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_edible_inventory_request_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryRecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryRecycleRequest) ProtoMessage() {}

func (x *InventoryRecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_edible_inventory_request_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryRecycleRequest.ProtoReflect.Descriptor instead.
func (*InventoryRecycleRequest) Descriptor() ([]byte, []int) {
	return file_protos_edible_inventory_request_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryRecycleRequest) GetRecycleFinished() bool {
	if x != nil {
		return x.RecycleFinished
	}
	return false
}

func (x *InventoryRecycleRequest) GetRecycleExpired() bool {
	if x != nil {
		return x.RecycleExpired
	}
	return false
}

// The request schema for calling Use on inventory.
type InventoryUseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FoodId uint32 `protobuf:"varint,1,opt,name=food_id,json=foodId,proto3" json:"food_id,omitempty"`
}

func (x *InventoryUseRequest) Reset() {
	*x = InventoryUseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_edible_inventory_request_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryUseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUseRequest) ProtoMessage() {}

func (x *InventoryUseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_edible_inventory_request_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUseRequest.ProtoReflect.Descriptor instead.
func (*InventoryUseRequest) Descriptor() ([]byte, []int) {
	return file_protos_edible_inventory_request_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryUseRequest) GetFoodId() uint32 {
	if x != nil {
		return x.FoodId
	}
	return 0
}

// The request schema for calling Buy on inventory.
type InventoryBuyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Amount    uint32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	ExpiresAt int64  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
}

func (x *InventoryBuyRequest) Reset() {
	*x = InventoryBuyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_edible_inventory_request_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryBuyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryBuyRequest) ProtoMessage() {}

func (x *InventoryBuyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_edible_inventory_request_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryBuyRequest.ProtoReflect.Descriptor instead.
func (*InventoryBuyRequest) Descriptor() ([]byte, []int) {
	return file_protos_edible_inventory_request_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryBuyRequest) GetAmount() uint32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *InventoryBuyRequest) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

var File_protos_edible_inventory_request_proto protoreflect.FileDescriptor

var file_protos_edible_inventory_request_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x64, 0x69, 0x62, 0x6c, 0x65, 0x2f,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x18, 0x65, 0x64, 0x69, 0x62, 0x6c, 0x65, 0x2e,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x6d, 0x0a, 0x17, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65,
	0x63, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x10,
	0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x5f, 0x66, 0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0f, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x46,
	0x69, 0x6e, 0x69, 0x73, 0x68, 0x65, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x72, 0x65, 0x63, 0x79, 0x63,
	0x6c, 0x65, 0x5f, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0e, 0x72, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x45, 0x78, 0x70, 0x69, 0x72, 0x65, 0x64,
	0x22, 0x2e, 0x0a, 0x13, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x6f, 0x6f, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x66, 0x6f, 0x6f, 0x64, 0x49, 0x64,
	0x22, 0x4c, 0x0a, 0x13, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x42, 0x75, 0x79,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x78, 0x70, 0x69, 0x72, 0x65, 0x73, 0x41, 0x74, 0x42, 0x09,
	0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x65, 0x69, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_protos_edible_inventory_request_proto_rawDescOnce sync.Once
	file_protos_edible_inventory_request_proto_rawDescData = file_protos_edible_inventory_request_proto_rawDesc
)

func file_protos_edible_inventory_request_proto_rawDescGZIP() []byte {
	file_protos_edible_inventory_request_proto_rawDescOnce.Do(func() {
		file_protos_edible_inventory_request_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_edible_inventory_request_proto_rawDescData)
	})
	return file_protos_edible_inventory_request_proto_rawDescData
}

var file_protos_edible_inventory_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_edible_inventory_request_proto_goTypes = []interface{}{
	(*InventoryRecycleRequest)(nil), // 0: edible.inventory.request.InventoryRecycleRequest
	(*InventoryUseRequest)(nil),     // 1: edible.inventory.request.InventoryUseRequest
	(*InventoryBuyRequest)(nil),     // 2: edible.inventory.request.InventoryBuyRequest
}
var file_protos_edible_inventory_request_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_edible_inventory_request_proto_init() }
func file_protos_edible_inventory_request_proto_init() {
	if File_protos_edible_inventory_request_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_edible_inventory_request_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryRecycleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_edible_inventory_request_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryUseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_edible_inventory_request_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryBuyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_edible_inventory_request_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_edible_inventory_request_proto_goTypes,
		DependencyIndexes: file_protos_edible_inventory_request_proto_depIdxs,
		MessageInfos:      file_protos_edible_inventory_request_proto_msgTypes,
	}.Build()
	File_protos_edible_inventory_request_proto = out.File
	file_protos_edible_inventory_request_proto_rawDesc = nil
	file_protos_edible_inventory_request_proto_goTypes = nil
	file_protos_edible_inventory_request_proto_depIdxs = nil
}
