// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.12.4
// source: protos/edible/inventory/response.proto

package eipb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The response you get for calling Recycle on inventory.
type InventoryRecycleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InventoryRecycleResponse) Reset() {
	*x = InventoryRecycleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_edible_inventory_response_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryRecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryRecycleResponse) ProtoMessage() {}

func (x *InventoryRecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_edible_inventory_response_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryRecycleResponse.ProtoReflect.Descriptor instead.
func (*InventoryRecycleResponse) Descriptor() ([]byte, []int) {
	return file_protos_edible_inventory_response_proto_rawDescGZIP(), []int{0}
}

func (x *InventoryRecycleResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// The response you get for calling Use on inventory.
type InventoryUseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InventoryUseResponse) Reset() {
	*x = InventoryUseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_edible_inventory_response_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryUseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryUseResponse) ProtoMessage() {}

func (x *InventoryUseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_edible_inventory_response_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryUseResponse.ProtoReflect.Descriptor instead.
func (*InventoryUseResponse) Descriptor() ([]byte, []int) {
	return file_protos_edible_inventory_response_proto_rawDescGZIP(), []int{1}
}

func (x *InventoryUseResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// The response you get for calling Buy on inventory.
type InventoryBuyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *InventoryBuyResponse) Reset() {
	*x = InventoryBuyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_edible_inventory_response_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InventoryBuyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InventoryBuyResponse) ProtoMessage() {}

func (x *InventoryBuyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_edible_inventory_response_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InventoryBuyResponse.ProtoReflect.Descriptor instead.
func (*InventoryBuyResponse) Descriptor() ([]byte, []int) {
	return file_protos_edible_inventory_response_proto_rawDescGZIP(), []int{2}
}

func (x *InventoryBuyResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_protos_edible_inventory_response_proto protoreflect.FileDescriptor

var file_protos_edible_inventory_response_proto_rawDesc = []byte{
	0x0a, 0x26, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x65, 0x64, 0x69, 0x62, 0x6c, 0x65, 0x2f,
	0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x19, 0x65, 0x64, 0x69, 0x62, 0x6c, 0x65,
	0x2e, 0x69, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x32, 0x0a, 0x18, 0x49, 0x6e, 0x76, 0x65, 0x6e, 0x74, 0x6f, 0x72, 0x79,
	0x52, 0x65, 0x63, 0x79, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2e, 0x0a, 0x14, 0x49, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x2e, 0x0a, 0x14, 0x49, 0x6e, 0x76, 0x65, 0x6e,
	0x74, 0x6f, 0x72, 0x79, 0x42, 0x75, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x3b, 0x65, 0x69,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_edible_inventory_response_proto_rawDescOnce sync.Once
	file_protos_edible_inventory_response_proto_rawDescData = file_protos_edible_inventory_response_proto_rawDesc
)

func file_protos_edible_inventory_response_proto_rawDescGZIP() []byte {
	file_protos_edible_inventory_response_proto_rawDescOnce.Do(func() {
		file_protos_edible_inventory_response_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_edible_inventory_response_proto_rawDescData)
	})
	return file_protos_edible_inventory_response_proto_rawDescData
}

var file_protos_edible_inventory_response_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_edible_inventory_response_proto_goTypes = []interface{}{
	(*InventoryRecycleResponse)(nil), // 0: edible.inventory.response.InventoryRecycleResponse
	(*InventoryUseResponse)(nil),     // 1: edible.inventory.response.InventoryUseResponse
	(*InventoryBuyResponse)(nil),     // 2: edible.inventory.response.InventoryBuyResponse
}
var file_protos_edible_inventory_response_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_edible_inventory_response_proto_init() }
func file_protos_edible_inventory_response_proto_init() {
	if File_protos_edible_inventory_response_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_edible_inventory_response_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryRecycleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_edible_inventory_response_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryUseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_edible_inventory_response_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InventoryBuyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_edible_inventory_response_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_edible_inventory_response_proto_goTypes,
		DependencyIndexes: file_protos_edible_inventory_response_proto_depIdxs,
		MessageInfos:      file_protos_edible_inventory_response_proto_msgTypes,
	}.Build()
	File_protos_edible_inventory_response_proto = out.File
	file_protos_edible_inventory_response_proto_rawDesc = nil
	file_protos_edible_inventory_response_proto_goTypes = nil
	file_protos_edible_inventory_response_proto_depIdxs = nil
}
